{
    "propertypage-name-label_css_class": "propertypage-name-label-nocap",
    "Script Editor": "鑴氭湰缂栬緫鍣�",
    " Published Charts Timeline": "鍙戣鏃堕棿",
    "SMA": "SMA绠€鍗曠Щ鍔ㄥ钩鍧囩嚎",
    "Bar's Style": "K绾挎牱寮�",
    "Chart Properties": "鍥捐〃灞炴€�",
    "Compare": "姣旇緝",
    "Compare...": "姣旇緝...",
    "Compare or Add Symbol...": "姣旇緝/澧炲姞鍟嗗搧...",
    "Compare or Add Symbol": "姣旇緝/澧炲姞鍟嗗搧",
    "Add Symbol": "澧炲姞鍟嗗搧",
    "Scales Properties...": "鍒诲害灞炴€�...",
    "Add": "澧炲姞",
    "Company Comparison": "璇疯緭鍏ュ姣斿晢鍝�",
    "Indicators, Fundamentals, Economy and Add-ons": "鎶€鏈寚鏍�",
    "Economy & Symbols": "姣旇緝/澧炲姞鍟嗗搧",
    "Bars": "缇庡浗绾�",
    "Candles": "铚＄儧绾�",
    "Hollow Candles": "绌哄績铚＄儧绾�",
    "Line": "绾垮舰鍥�",
    "Area": "灞卞舰鍥�",
    "Heiken Ashi": "Heiken Ashi鍥�",
    "Histogram": "鐩存柟鍥�",
    "Cross_chart_type": "鍗佸瓧鍥�",
    "Crosshair": "鍗佸瓧",
    "Columns": "鏌辩姸鍥�",
    "Circles": "鍦嗗湀鍥�",
    "Indicators": "鎶€鏈寚鏍�",
    "Favorites": "鍋忓ソ",
    "Technical Analysis": "鎶€鏈垎鏋�",
    "No indicators matched your criteria.": "娌℃湁鎸囨爣绗﹀悎鎮ㄧ殑鎼滅储鏉′欢.",
    "Add to favorites": "澧炲姞鍒板亸濂戒腑",
    "Remove from favorites": "浠庡亸濂戒腑绉婚櫎",
    "No symbols matched your criteria": "娌℃湁鍟嗗搧绗﹀悎鎮ㄧ殑鎼滅储鏉′欢.",
    "Add any symbol from the list": "浠庡垪琛ㄤ腑娣诲姞涓€浜涘晢鍝�",
    "Overlay the main chart": "鍦ㄤ富鍥句笂鏄剧ず",
    "Symbols to be added on the chart": "鎻掑叆鍟嗗搧鍒板浘琛ㄤ笂",
    "Symbol": "鍟嗗搧",
    "Default": "绯荤粺榛樿",
    "Defaults": "棰勮鍊�",
    "OK": "纭",
    "Cancel": "鍙栨秷",
    " color": "棰滆壊",
    " transparency": "閫忔槑搴�",
    " visibility": "鑳借搴�",
    "Add To Watchlist": "娣诲姞鍒版敹钘忓す",
    "Apply": "搴旂敤",
    "Arguments in Header": "琛ㄥご鍙傛暟",
    "Arrow": "绠ご",
    "Auto Scale": "鑷姩缂╂斁",
    "Background": "鑳屾櫙",
    "bars": "鏍筀绾�",
    "bars_margin": "鏍筀绾�",
    "{0} bars": "{0}鏍筀绾�",
    "Bottom Margin": "涓嬭竟璺�",
    "Bring Forward": "鍚戜笂绉诲姩",
    "Bring to Front": "缃簬椤跺眰",
    "Clone": "鍏嬮殕",
    "Color Theme": "涓婚棰滆壊",
    "Copy": "澶嶅埗",
    "Extended Hours": "寤舵椂",
    "Format...": "璁剧疆...",
    "Full Screen": "鍏ㄥ睆鏄剧ず",
    "Grid Lines": "缃戞牸绾�",
    "Hide All Drawing Tools": "闅愯棌鎵€鏈夌粯鍥惧伐鍏�",
    "Hide": "闅愯棌",
    "Insert Drawing Tool": "鎻掑叆缁樺浘宸ュ叿",
    "Insert Indicator...": "鎻掑叆鎶€鏈寚鏍�",
    "Last Value on Price Scale": "鍦ㄤ环鏍煎埢搴︿笂鏄剧ず鏈€缁堝€�",
    "Link To": "閾炬帴鍒�",
    "Load New Bars": "鍔犺浇鏂扮殑K绾�",
    "Lock All Drawing Tools": "閿佸畾鎵€鏈夌粯鍥�",
    "Lock Scale": "閿佸畾鍒诲害",
    "Lock scale": "閿佸畾鍒诲害",
    "Log Scale": "瀵规暟鍒诲害",
    "log": "瀵规暟鍒诲害",
    "Magnet Mode": "纾侀搧妯″紡",
    "Merge Down": "鍚戜笅鍚堝苟",
    "Merge Up": "鍚戜笂鍚堝苟",
    "Objects Tree...": "绠＄悊璁惧畾...",
    "Offset": "鍋忕Щ",
    "Override Min Tick": "鏄剧ず鏈€灏忓埢搴�",
    "Percentage": "鐧惧垎姣�",
    "Precision": "绮剧‘搴�",
    "Price Line": "浠锋牸绾�",
    "Properties...": "灞炴€�...",
    "Redo": "閲嶅仛",
    "Remove All Drawing Tools": "绉婚櫎鎵€鏈夌粯鍥�",
    "Remove All Studies": "绉婚櫎鎵€鏈夊叕寮�",
    "Remove All Indicators": "绉婚櫎鎵€鏈夋寚鏍�",
    "Remove": "绉婚櫎",
    "Reset Chart": "閲嶈鍥捐〃",
    "Reset Scale": "閲嶈鍒诲害",
    "Reset": "閲嶈",
    "Right Margin": "鍙宠竟璺�",
    "Save As...": "鍙﹀瓨涓�...",
    "Scale Left": "缂╂斁宸﹁竟",
    "Scale Percentage": "鍒诲害姣斾緥",
    "Scale Right": "缂╂斁鍙宠竟",
    "Scale Series Only": "鍙缉鏀炬暟鎹郴鍒�",
    "Scale series only": "鍙缉鏀炬暟鎹郴鍒�",
    "Scale Series only": "鍙缉鏀炬暟鎹郴鍒�",
    "Scales Lines": "鍒诲害绾�",
    "Scales Text": "鍒诲害鏂囧瓧",
    "Scaling": "缂╂斁",
    "Screen (No Scale)": "灞忓箷(鏃犵缉鏀�)",
    "Send Backward": "涓嬬Щ涓€灞�",
    "Send to Back": "缃簬搴曞眰",
    "Session Breaks": "鏀剁洏鏃朵腑鏂�",
    "Show Arguments in Header": "鍦ㄨ〃澶翠笂鏄剧ず鍙傛暟",
    "Show Last Value on Price Scale": "鏄剧ず鏈€鍚庢敹鐩樹环",
    "Show Left Axis": "鏄剧ず宸﹁酱",
    "Show Right Axis": "鏄剧ず鍙宠酱",
    "Show": "鏄剧ず",
    "Stay In Drawing Mode": "淇濇寔缁樺浘妯″紡",
    "Symbol Search...": "鏌ユ壘鍟嗗搧...",
    "Change Symbol": "淇敼鍟嗗搧",
    "Change Symbol...": "淇敼鍟嗗搧...",
    "Time Zone": "鏃跺尯",
    "TimeZone": "鏃跺尯",
    "Top Margin": "涓婅竟璺�",
    "Transparency": "閫忔槑搴�",
    "Undo {0}": "鎾ら攢",
    "Undo": "鎾ら攢",
    "Unmerge Down": "鍙栨秷鍚戜笅鍚堝苟",
    "Unmerge Up": "鍙栨秷鍚戜笂鍚堝苟",
    "Visual Order": "瑙嗚鎺掑簭",
    "Watermark": "姘村嵃",
    "Show Objects Tree": "鏄剧ず绠＄悊璁惧畾",
    "cursors-group-css-class": "cursors-group-css-class",
    "ABCD Pattern": "ABCD 鍨嬫€�",
    "Anchored Text": "閿氱偣鏂囨湰",
    "Arc": "寮у舰",
    "Arrow Mark Down": "鍚戜笅绠ご",
    "Arrow Mark Left": "鍚戝乏绠ご",
    "Arrow Mark Right": "鍚戝彸绠ご",
    "Arrow Mark Up": "鍚戜笂绠ご",
    "Balloon": "娉℃场娉ㄨВ",
    "Bars Pattern": "绔栨潯妯″瀷",
    "Brush": "绗斿埛",
    "Callout": "鏍囨敞",
    "Circle Lines": "鍦嗗舰绾垮湀",
    "Cross": "鍗佸瓧鎸囬拡",
    "Cyclic Lines": "寰幆绾�",
    "Date Range": "鏃ユ湡鑼冨洿",
    "Disjoint Angle": "涓嶇浉浜ょ殑瑙�",
    "Dot": "鍦嗙偣",
    "Elliott Labels": "鑹剧暐鐗规爣绛�",
    "Elliott Major Retracement": "鑹剧暐鐗逛富娉㈡氮鍥炴挙",
    "Elliott Minor Retracement": "鑹剧暐鐗瑰皬娉㈡氮鍥炴挙",
    "Elliott Wave Cycle": "鑹剧暐鐗瑰惊鐜尝",
    "Elliott Wave Minor": "鑹剧暐鐗瑰皬鍨嬫尝",
    "Elliott Wave Subminuette": "鑹剧暐鐗规寰尝",
    "Ellipse": "妞渾褰�",
    "Eraser": "娓呴櫎",
    "Extended": "寤朵几",
    "Extended Line": "寤朵几绾�",
    "Fib Channel": "鏂愭尝閭ｅ閫氶亾",
    "Fib Circles": "鏂愭尝閭ｅ鍦�",
    "Fib Retracement": "鏂愭尝閭ｅ鍥炴挙",
    "Fib Speed Resistance Arcs": "鏂愭尝閭ｅ閫熷害闃诲姏寮�",
    "Fib Speed Resistance Fan": "鏂愭尝閭ｅ閫熷害闃诲姏鎵�",
    "Fib Spiral": "鏂愭尝閭ｅ铻烘棆",
    "Fib Time Zone": "鏂愭尝閭ｅ鏃堕棿鍛ㄦ湡",
    "Fib Wedge": "妤斿舰鏂愭尝閭ｅ",
    "Flag Mark": "鏃楀瀷鏍囪",
    "Flat Top/Bottom": "骞虫粦椤堕儴/搴曢儴",
    "Flat Bottom": "骞虫粦搴曢儴",
    "Forecast": "棰勬祴",
    "Gann Box": "绠卞舰鐢樻皬绾�",
    "Gann Fan": "鎵囧舰鐢樻皬绾�",
    "Gann Square": "鏂瑰舰鐢樻皬绾�",
    "Head & Shoulders": "澶磋偐椤�",
    "Horizontal Line": "姘村钩绾�",
    "Horizontal Ray": "姘村钩灏勭嚎",
    "Icon": "鍥炬爣",
    "Inside Pitchfork": "鍐呴儴鍒嗗弶绾�",
    "Long Position": "澶氬ご",
    "Risk/Reward long": "澶氬ご椋庨櫓/鍥炴姤姣斾緥",
    "Modified Schiff Pitchfork": "璋冩暣甯屽か鍒嗗弶绾�",
    "Parallel Channel": "骞宠閫氶亾",
    "Pitchfan": "鍊炬枩鎵囧舰",
    "Pitchfork": "鍒嗗弶绾�",
    "Polyline": "澶氳竟褰�",
    "Price Label": "浠锋牸鏍囩",
    "Price Range": "浠锋牸鑼冨洿",
    "Projection": "鎶曞奖",
    "Ray": "灏勭嚎",
    "Rectangle": "鐭╁舰",
    "Regression Trend": "鍥炲綊瓒嬪娍",
    "Rotated Rectangle": "鏃嬭浆鐭╁舰",
    "Schiff Pitchfork": "甯屽か鍒嗗弶绾�",
    "Schiff": "甯屽か",
    "Original": "鍘熷瀷",
    "Modified Schiff": "璋冩暣甯屽か",
    "Inside": "鍐呴儴",
    "Short Position": "绌哄ご",
    "Risk/Reward short": "绌哄ご椋庨櫓/鍥炴姤姣斾緥",
    "Text": "鏂囨湰",
    "Comment": "璇勮",
    "Three Drivers Pattern": "涓夐┍鍔ㄥ瀷鎬�",
    "Thumb Down": "澶ф媷鎸囧悜涓�",
    "Thumb Up": "绔栬捣澶ф媷鎸�",
    "Trend Angle": "瓒嬪娍鐨勮搴�",
    "Trend Line": "瓒嬪娍绾�",
    "Trend-Based Fib Extension": "鏂愭尝閭ｅ瓒嬪娍鎵╁睍",
    "Trend-Based Fib Time": "鏂愭尝閭ｅ瓒嬪娍鏃堕棿",
    "Triangle Pattern": "涓夎鍨嬫€�",
    "Triangle": "涓夎褰�",
    "Vertical Line": "鍨傜洿绾�",
    "XABCD Pattern": "XABCD 鍨嬫€�",
    "Angle:": "瑙掑害",
    "Arcs": "寮у舰",
    "Background color 1": "鑳屾櫙棰滆壊1",
    "Background color 2": "鑳屾櫙棰滆壊2",
    "Background Color": "鑳屾櫙棰滆壊",
    "Bar #": "K绾�#",
    "Border color": "杈规棰滆壊",
    "Border Color": "杈规棰滆壊",
    "Border": "杈规",
    "Bottom Lables": "搴曢儴鏍囩",
    "bottom": "搴曢儴",
    "center": "涓績",
    "Channel": "閫氶亾",
    "Coeffs As Percents": "鐧惧垎姣旂郴鏁�",
    "Color bars based on previous close": "bar棰滆壊鍩轰簬鍓嶄竴鏀剁洏浠�",
    "Color": "棰滆壊",
    "Color:": "棰滆壊:",
    "Coordinates": "鍧愭爣",
    "Delete": "鍒犻櫎",
    "Down Color": "涓嬫媺棰滆壊",
    "Drawings": "缁樺浘",
    "Entry price:": "杩涘満浠�:",
    "Events": "浜嬩欢",
    "Extend Left End": "宸︾寤朵几",
    "Extend Left": "鍚戝乏寤朵几",
    "Extend Lines": "寤堕暱绾�",
    "Extend Right End": "鍙崇寤朵几",
    "Extend Right": "鍚戝彸寤朵几",
    "Extend": "寤朵几",
    "Failure back color": "澶辫触鐨勮儗鏅鑹�",
    "Failure text color": "澶辫触鐨勬枃鏈鑹�",
    "Fans": "鎵囧舰",
    "Fill": "濉厖",
    "Format": "璁剧疆",
    "Graphics": "鍥惧儚",
    "Grid": "缃戞牸",
    "Help": "甯姪",
    "HLC Bars": "HLC绾�",
    "Inputs": "鍙傛暟",
    "Label Background": "鏍囩鑳屾櫙鑹�",
    "Label": "鏍囩",
    "Labels": "鏍囩",
    "Left End": "宸︾",
    "Left Labels": "宸﹁竟鏍囩",
    "left": "宸﹁竟",
    "Level {0}": "绛夌骇{0}",
    "Levels": "绛夌骇",
    "Lines": "绾挎潯",
    "Major": "涓昏绾�",
    "Measure (Shift + Click on the chart)": "娴嬮噺 (鎸塖hift骞剁偣鍑诲浘琛�)",
    "Median": "涓嚎",
    "middle": "涓棿",
    "Middle": "涓棿",
    "Minor": "灏忓瀷绾�",
    "Mode": "妯″紡",
    "Normal": "涓€鑸�",
    "Plot": "鐢荤嚎",
    "Price Levels": "浠锋牸绛夌骇",
    "Price Source": "鏉ユ簮",
    "Price": "浠锋牸",
    "Price:": "浠锋牸:",
    "Prices": "浠锋牸",
    "Profit Background Color": "鍒╂鼎鑳屾櫙棰滆壊",
    "Profit Level. Ticks:": "鑾峰埄.鏈€灏忓埢搴︽暟:",
    "Properties": "灞炴€�",
    "Reverse": "鍙嶅悜",
    "Right End": "鍙崇",
    "Right Lables": "鍙宠竟鏍囩",
    "right": "鍙宠竟",
    "Log Scale_scale_menu": "瀵规暟鍒诲害",
    "Percentage_scale_menu": "鐧惧垎姣斿埢搴�",
    "Scales": "鍒诲害",
    "Settings": "璁剧疆",
    "Show Background": "鏄剧ず鑳屾櫙",
    "Show Bars Range": "鏄剧ずK绾垮尯闂�",
    "Show Date/Time Range": "鏄剧ず鏃ユ湡/鏃堕棿鍖洪棿",
    "Show Distance": "鏄剧ず璺濈",
    "Show Labels": "鏄剧ず鏍囩",
    "Show Price Range": "鏄剧ず浠锋牸鍖洪棿",
    "Show Price": "鏄剧ず浠锋牸",
    "Show Prices": "鏄剧ず浠锋牸",
    "Show Text": "鏄剧ず鏂囨湰",
    "Show Time": "鏄剧ず鏃堕棿",
    "Show Wave": "鏄剧ず娉㈠舰",
    "Show/Hide": "鏄剧ず/闅愯棌",
    "Source back color": "璧风偣鑳屾櫙棰滆壊",
    "Source border color": "璧风偣杈规棰滆壊",
    "Source text color": "璧风偣鏂囨湰棰滆壊",
    "Stay in Drawing Mode": "淇濇寔缁樺浘妯″紡",
    "Stop Background Color": "姝㈡崯鑳屾櫙棰滆壊",
    "Stop Color:": "姝㈡崯棰滆壊:",
    "Stop Level. Ticks:": "姝㈡崯.鏈€灏忓埢搴︽暟:",
    "Style": "鏍峰紡",
    "Success back color": "鎴愬姛鐨勮儗鏅鑹�",
    "Success text color": "鎴愬姛鐨勬枃鏈鑹�",
    "Target back color": "缁堢偣鑳屾櫙棰滆壊",
    "Target border color": "缁堢偣杈规棰滆壊",
    "Target Color:": "鑾峰埄棰滆壊:",
    "Target text color": "鑾峰埄鏂囨湰棰滆壊",
    "Text Alignment:": "鏂囨湰瀵归綈:",
    "Text color": "鏂囨湰棰滆壊",
    "Text Color": "鏂囨湰棰滆壊",
    "Text Font": "鏂囨湰瀛椾綋",
    "Text Wrap": "鑷姩鎹㈣",
    "Text:": "鏂囨湰:",
    "Time Levels": "鏃堕棿绛夌骇",
    "Timezone/Sessions": "鏃跺尯",
    "Top Labels": "椤堕儴鏍囩",
    "top": "椤堕儴",
    "Up Color": "涓婃定棰滆壊",
    "Wave Size": "娉㈠舰澶у皬",
    "Wick": "鐑涜姱",
    "Zoom In": "鏀惧ぇ",
    "Zoom Out": "缂╁皬",
    "Borders": "杈规",
    "Level": "绛夌骇",
    "Hlines Background": "绐佹樉鑳屾櫙",
    "Plots Background": "缁樺埗鑳屾櫙",
    "Open_line_tool_position": "鏈钩浠�",
    "Closed_line_tool_position": "宸插钩浠�",
    "{0} P&L: {1}": "{0} 鑾峰埄&姝㈡崯: {1}",
    "Risk/Reward Ratio: {0}": "椋庨櫓/鍥炴姤姣旂巼: {0}",
    "Stop: {0} ({1}%)": "姝㈡崯: {0} ({1}%)",
    "Target: {0} ({1}%)": "鑾峰埄: {0} ({1}%)",
    "SUCCESS": "鎴愬姛",
    "FAILURE": "澶辫触",
    "Left Shoulder": "宸﹁偐",
    "Head": "澶撮《",
    "Right Shoulder": "鍙宠偐",
    "Mirrored": "鍨傜洿缈昏浆",
    "Flipped": "姘村钩缈昏浆",
    "distance: {0}": "璺濈: {0}",
    "day": "鏃�",
    "day_plural": "鏃�",
    "day_plural_1": "鏃�",
    "day_plural_2": "鏃�",
    "day_plural_5": "鏃�",
    "week": "鍛�",
    "week_plural": "鍛�",
    "week_plural_1": "鍛�",
    "week_plural_2": "鍛�",
    "week_plural_5": "鍛�",
    "month": "鏈�",
    "month_plural": "鏈�",
    "month_plural_1": "鏈�",
    "month_plural_2": "鏈�",
    "month_plural_5": "鏈�",
    "minute": "鍒�",
    "minute_plural": "鍒�",
    "minute_plural_1": "鍒�",
    "minute_plural_2": "鍒�",
    "minute_plural_5": "鍒�",
    "hour": "灏忔椂",
    "hour_plural": "灏忔椂",
    "hour_plural_1": "灏忔椂",
    "hour_plural_2": "灏忔椂`",
    "hour_plural_5": "灏忔椂",
    "y_dates": "骞�",
    "y_dates_plural": "骞�",
    "y_dates_plural_1": "骞�",
    "y_dates_plural_2": "骞�",
    "y_dates_plural_5": "骞�",
    "h_dates": "灏忔椂",
    "D_dates": "鏃�",
    "W_dates": "鍛�",
    "M_dates": "鏈�",
    "d_dates": "鏃�",
    "m_dates": "鍒�",
    "in_dates": "鎬�",
    "Jan": "涓€鏈�",
    "Feb": "浜屾湀",
    "Mar": "涓夋湀",
    "Apr": "鍥涙湀",
    "May": "浜旀湀",
    "Jun": "鍏湀",
    "Jul": "涓冩湀",
    "Aug": "鍏湀",
    "Sep": "涔濇湀",
    "Oct": "鍗佹湀",
    "Nov": "鍗佷竴鏈�",
    "Dec": "鍗佷簩鏈�",
    "Objects Tree": "绠＄悊璁惧畾",
    "Manage Drawings": "绠＄悊缁樺浘",
    "TOOL": "宸ュ叿",
    "SYMBOL": "鍟嗗搧",
    "Move Up": "涓婄Щ",
    "Move Down": "涓嬬Щ",
    "All Exchanges": "鎵€鏈夌殑浜ゆ槗鎵€",
    "All types": "鎵€鏈夌被鍨�",
    "Stock": "鑲＄エ",
    "stock": "鑲＄エ",
    "Index": "鎸囨暟",
    "index": "鎸囨暟",
    "Futures": "鏈熻揣",
    "futures": "鏈熻揣",
    "Image URL": "鍥剧墖缃戝潃",
    "Save image": "淇濆瓨鍥捐薄",
    "or copy url:": "鎴栧鍒剁綉鍧€:",
    "Redo {0}": "閲嶅仛{0}",
    "Custom color...": "鑷畾涔夐鑹�...",
    "Search": "鏌ユ壘",
    "Open_in_legend": "寮€=",
    "High_in_legend": "楂�=",
    "Low_in_legend": "浣�=",
    "Close_in_legend": "鏀�=",
    "Open": "寮€鐩樹环",
    "High": "鏈€楂樹环",
    "Low": "鏈€浣庝环",
    "Close": "鏀剁洏浠�",
    "(H + L)/2": "(H+L)/2",
    "(H + L + C)/3": "(H+L+C)/3",
    "(O + H + L + C)/4": "(O+H+L+C)/4",
    "UTC": "涓栫晫缁熶竴鏃堕棿",
    "Exchange": "浜ゆ槗鎵€",
    "Athens": "娆ф床/闆呭吀",
    "Berlin": "娆ф床/鏌忔灄",
    "Bogota": "鍗楃編娲�/娉㈠摜澶�",
    "Bangkok": "浜氭床/鏇艰胺",
    "Buenos Aires": "鍗楃編娲�/甯冨疁璇烘柉鑹惧埄鏂�",
    "Chicago": "鍖楃編娲�/鑺濆姞鍝�",
    "Hong Kong": "浜氭床/棣欐腐",
    "Kolkata": "浜氭床/鍔犲皵鍚勭瓟",
    "London": "娆ф床/浼︽暒",
    "Los Angeles": "鍖楃編娲�/娲涙潐鐭�",
    "Madrid": "娆ф床/椹痉閲�",
    "Moscow": "娆ф床/鑾柉绉�",
    "New York": "鍖楃編娲�/绾界害",
    "Paris": "娆ф床/宸撮粠",
    "Seoul": "浜氭床/棣栧皵",
    "Shanghai": "浜氭床/涓婃捣",
    "Singapore": "浜氭床/鏂板姞鍧�",
    "Sydney": "澶ф磱娲�/鎮夊凹",
    "Taipei": "浜氭床/鍙板寳",
    "Tehran": "浜氭床/寰烽粦鍏�",
    "Tokyo": "浜氭床/涓滀含",
    "Toronto": "鍖楃編娲�/澶氫鸡澶�",
    "Vancouver": "鍖楃編娲�/娓╁摜鍗�",
    "Warsaw": "娆ф床/鍗庢矙",
    "n/a": "n/a",
    "Long_input": "闀垮懆鏈�",
    "long_input": "闀垮懆鏈�",
    "longlen_input": "闀垮懆鏈�",
    "Window Size_input": "绐楀彛澶у皬",
    "Length_input": "闀垮害",
    "length_input": "闀垮害",
    "len_input": "闀垮害",
    "Short_input": "鐭懆鏈�",
    "short_input": "鐭懆鏈�",
    "shortlen_input": "鐭懆鏈�",
    "Mult_input": "涔樻暟",
    "mult_input": "涔樻暟",
    "divisor_input": "闄ゆ暟",
    "Divisor_input": "闄ゆ暟",
    "Upper": "涓婅建",
    "Lower": "涓嬭建",
    "Long": "涔拌繘",
    "Short": "鍗栧嚭",
    "Signal": "淇″彿",
    "Jaw": "涓嬮",
    "Teeth": "鐗欓娇",
    "Lips": "鍢村攪",
    "Zero": "闆惰酱",
    "WMA Length_input": "WMA闀垮害",
    "Long RoC Length_input": "RoC 闀垮懆鏈�",
    "Short RoC Length_input": "RoC 鐭懆鏈�",
    "jawLength_input": "涓嬮闀垮害",
    "teethLength_input": "鐗欓娇闀垮害",
    "lipsLength_input": "鍢村攪闀垮害",
    "percent_input": "鐧惧垎姣�",
    "exponential_input": "鎸囨暟",
    "smoothD_input": "骞虫粦 %D(SK)",
    "smoothK_input": "骞虫粦 %K(SK)",
    "Color 0": "棰滆壊 0",
    "Color 1": "棰滆壊 1",
    "Color 2": "棰滆壊 2",
    "Color 3": "棰滆壊 3",
    "Color 4": "棰滆壊 4",
    "sym_input": "鍟嗗搧浠ｇ爜",
    "symbol_input": "鍟嗗搧浠ｇ爜",
    "Sym_input": "鍟嗗搧浠ｇ爜",
    "DI Length_input": "DI 闀垮害",
    "ADX Smoothing_input": "骞虫粦ADX",
    "displacement_input": "鍋忕Щ",
    "Tenkan-sen": "淇″彿绾�",
    "Kijun-sen": "鍩虹绾�",
    "Chikou span": "寤惰繜绾�",
    "Senkou A": "涓婁簯灞� A",
    "Senkou B": "涓嬩簯灞� B",
    "useTrueRange_input": "浣跨敤鐪熷疄娉㈠箙",
    "roclen1_input": "RoC 闀垮害1",
    "roclen2_input": "RoC 闀垮害2",
    "roclen3_input": "RoC 闀垮害3",
    "roclen4_input": "RoC 闀垮害4",
    "smalen1_input": "SMA 闀垮害1",
    "smalen2_input": "SMA 闀垮害2",
    "smalen3_input": "SMA 闀垮害3",
    "smalen4_input": "SMA 闀垮害4",
    "siglen_input": "淇″彿闀垮害",
    "UpperLimit": "涓婇檺",
    "LowerLimit": "涓嬮檺",
    "fastLength_input": "蹇€熷懆鏈�",
    "slowLength_input": "鎱㈤€熷懆鏈�",
    "signalLength_input": "淇″彿闀垮害",
    "start_input": "寮€濮嬪€�",
    "increment_input": "澧為噺",
    "maximum_input": "鏈€澶у€�",
    "showMA_input": "鏄剧ず鎴愪氦閲忕Щ鍔ㄥ钩鍧�",
    "show MA_input": "鏄剧ず鎴愪氦閲忕Щ鍔ㄥ钩鍧�",
    "Volume": "鎴愪氦閲�",
    "Volume MA": "鎴愪氦閲忕Щ鍔ㄥ钩鍧�",
    "Indicator": "鎸囨爣",
    "Oscillator": "鎽嗗姩",
    "lengthStoch_input": "Stoch闀垮害",
    "lengthRSI_input": "RSI闀垮害",
    "sigma_input": "sigma(鈭�)",
    "Sigma_input": "Sigma(鈭�)",
    "Crosses": "鍗佸瓧绾�",
    "Click to set a point": "鍗曞嚮璁剧疆鐐�",
    "1. Slide your finger to select location for first anchor<br>2. Tap anywhere to place the first anchor": "1.鎷栧姩鍗佸瓧绾垮畾涔夌涓€鐐�.<br/>2.鐐瑰嚮浠绘剰浣嶇疆纭畾绗竴涓仠姝綅缃�",
    "1. Slide your finger to select location for next anchor<br>2. Tap anywhere to place the next anchor": "1.鎷栧姩鍗佸瓧绾垮畾涔夌涓€鐐�.<br/>2.鐐瑰嚮浠绘剰浣嶇疆纭畾绗竴涓仠姝綅缃�",
    "retrying": "閲嶈瘯",
    "eod data": "鏃ヨ祫鏂�",
    "eod delayed": "寤惰繜鏃ヨ祫鏂�",
    "loading data": "鍔犺浇鏁版嵁",
    "invalid symbol": "鏃犳晥鐨勫晢鍝佷唬鐮�",
    "streaming": "娴佸獟浣�",
    "realtime": "瀹炴椂",
    "pre-market": "寮€甯傚墠",
    "post-market": "闂競鍚�",
    "closed": "鏀剁洏",
    "Time Interval": "鏃堕棿鍛ㄦ湡",
    "Show Symbol Labels": "鏄剧ず鍟嗗搧浠ｇ爜鏍囩",
    "Show Symbol Labels_context_menu": "鏄剧ず鍟嗗搧浠ｇ爜鏍囩",
    "Subminuette": "娆″井绾�",
    "Minuette": "寰骇",
    "Minute": "缁嗙骇",
    "Intermediate": "涓瀷绾�",
    "Primary": "鍩烘湰绾�",
    "Cycle": "寰幆绾�",
    "SuperCycle": "瓒呯骇寰幆绾�",
    "GrandSuperCycle": "鐗瑰ぇ瓒呯骇寰幆绾�",
    "Lock": "閿佸畾",
    "Width": "瀹藉害",
    "Line With Breaks": "涓柇绾�",
    "Area With Breaks": "涓柇鍖哄潡",
    "Type": "绫诲瀷",
    "Simple": "绠€鍗�",
    "With Markers": "甯︽爣璁�",
    "Step": "闃舵",
    "No drawings yet": "灏氭湭缁樺浘",
    "Lock/Unlock": "閿佸畾/瑙ｉ攣",
    "deviation_input": "鏍囧噯宸�",
    "depth_input": "娣卞害",
    "Accumulation/Distribution_study": "绱Н/娲惧彂鎸囨爣(Accum/Dist)",
    "Aroon_study": "闃块殕鎸囨爣(Aroon)",
    "Advance/Decline_study": "鑵捐惤鎸囨爣(AD)",
    "Average True Range_study": "骞冲潎鐪熷疄娉㈠箙(ATR)",
    "Awesome Oscillator_study": "鍔ㄩ噺闇囪崱鎸囨爣(AO)",
    "Bollinger Bands Width_study": "甯冩灄甯﹀(BBW)",
    "Balance of Power_study": "鍔涢噺骞宠　搴︽寚鏍�(Balance of Power)",
    "Bollinger Bands_study": "甯冩灄绾挎寚鏍�(BB)",
    "Bollinger Bands %B_study": "甯冩灄鏋侀檺(BB%B)",
    "Chaikin Money Flow_study": "钄￠噾璐у竵娴侀噺(CMF)",
    "Chaikin Oscillator_study": "钄￠噾鎽嗗姩鎸囨爣(Chaikin Osc)",
    "Chande Kroll Stop_study": "閽卞痉鍏嬬綏姝㈡崯(Chande Kroll Stop)",
    "Chande Momentum Oscillator_study": "閽卞痉鍔ㄩ噺鎽嗗姩鎸囨爣(ChandeMO)",
    "Commodity Channel Index_study": "椤哄娍鎸囨爣(CCI)",
    "Choppiness Index_study": "娉㈠姩鎸囨爣(CHOP)",
    "Directional Movement Index_study": "瓒嬪悜鎸囨爣(DMI)",
    "Correlation Coeff_study": "鐩稿叧绯绘暟(CC)",
    "Donchian Channels_study": "鍞愬瀹夐€氶亾鎸囨爣(DC)",
    "Double Exponential Moving Average_study": "鍙岄噸鎸囨暟绉诲姩骞冲潎绾�(DEMA)",
    "Ease of Movement_study": "绠€鏄撴尝鍔ㄦ寚鏍�(EOM)",
    "Elders Force Index_study": "寮哄姏鎸囨暟鎸囨爣(EFI)",
    "Envelope_study": "鍖呯粶绾挎寚鏍�(Env)",
    "Ichimoku Cloud_study": "涓€鐩潎琛¤〃(Ichimoku)",
    "Klinger Oscillator_study": "鍏嬮噷鏍兼尟鑽″櫒(Klinger Osc)",
    "Hull MA_study": "鑸逛綋绉诲姩骞冲潎绾�(HMA)",
    "Keltner Channels_study": "鑲壒绾抽€氶亾(KC)",
    "Linear Regression Curve_study": "绾挎€у洖褰掓洸绾�(LRC)",
    "Know Sure Thing_study": "鍔犳潈鎬诲拰鍙樺姩鐜�(KST)",
    "MA Cross_study": "绉诲姩骞冲潎浜ゅ弶绾�(MA Cross)",
    "Money Flow_study": "璧勯噾娴侀噺鎸囨爣(MFI)",
    "Mass Index_study": "姊呮柉绾�(MASS)",
    "Moving Average Exponential_study": "鎸囨暟绉诲姩骞冲潎绾�(EMA)",
    "Net Volume_study": "鍑€浜ゆ槗閲�(NetVol)",
    "Moving Average Convergence/Divergence_study": "骞虫粦寮傚悓骞冲潎鎸囨爣(MACD)",
    "Moving Average_study": "绉诲姩骞冲潎绾�(MA)",
    "Moving Average Weighted_study": "鍔犳潈绉诲姩骞冲潎绾�(WMA)",
    "Parabolic SAR_study": "鎶涚墿绾胯浆鍚戞寚鏍�(SAR)",
    "On Balance Volume_study": "骞宠　浜ゆ槗閲忔寚鏍�(OBV)",
    "Price Oscillator_study": "浠锋牸鎸崱鎸囨爣(PPO)",
    "Relative Strength Index_study": "鐩稿寮哄急鎸囨暟鎸囨爣(RSI)",
    "Relative Vigor Index_study": "鐩稿鑳介噺鎸囨暟鎸囨爣(RVGI)",
    "Relative Volatility Index_study": "鐩稿绂绘暎鎸囨暟鎸囨爣(RVI)",
    "SMI Ergodic Indicator/Oscillator_study": "鍚勬€佸巻缁廠MI(SMIIO)",
    "Stochastic_study": "闅忔満鎸囨爣(STOCH)",
    "TRIX_study": "涓夐噸鎸囨暟骞冲潎绾�(TRIX)",
    "Stochastic RSI_study": "闅忔満寮哄急鎸囨暟(STOCH RSI)",
    "Triple EMA_study": "涓夐噸鎸囨暟绉诲姩骞冲潎绾�(TEMA)",
    "VWMA_study": "鎴愪氦閲忓姞鏉冪殑绉诲姩骞冲潎鍊�(VWMA)",
    "Volume Oscillator_study": "鎴愪氦閲忛渿鑽�(Volume Osc)",
    "Volume_study": "鎴愪氦閲�",
    "Williams Alligator_study": "槌勯奔绾�(Alligator)",
    "Willams %R_study": "濞佸粔鎸囨爣(%R)",
    "Coppock Curve_study": "浼版尝鏇茬嚎(Coppock Curve)",
    "Least Squares Moving Average_study": "鏈€灏忎簩涔樼Щ鍔ㄥ钩鍧囩嚎(LSMA)",
    "Arnaud Legoux Moving Average_study": "Arnaud Legoux鍧囩嚎(ALMA)",
    "True Strength Indicator_study": "鐪熷疄寮哄害鎸囨爣(TSI)",
    "Change Interval": "璁剧疆鍛ㄦ湡",
    "Show Only Studies": "鍙樉绀哄叕寮�",
    "Show Only Drawings": "鍙樉绀虹粯鍥�",
    "Show All": "鍏ㄩ儴鏄剧ず",
    "Timezone/Sessions Properties...": "鏃跺尯灞炴€�...",
    "Scale Price Chart Only": "鍙缉鏀句环浣嶅浘灞�",
    "Open Interval Dialog": "鎵撳紑璁剧疆鍛ㄦ湡",
    "Note": "娉ㄩ噴",
    "Anchored Note": "閿氱偣娉ㄩ噴",
    "Scales Properties": "鍒诲害灞炴€�",
    "Toggle Auto Scale": "鍒囨崲涓鸿嚜鍔ㄧ缉鏀�",
    "Toggle Log Scale": "鍒囨崲涓哄鏁扮缉鏀�",
    "Toggle Percentage": "鍒囨崲涓虹櫨鍒嗘瘮",
    "auto_scale": "鑷姩",
    "Invalid Symbol": "鏃犳晥鐨勬爣鐨�",
    "loading...": "杞藉叆涓�...",
    "interval_dialog_description": "鑻ラ噰鐢ㄥ垎閽熷懆鏈燂紝璇疯緭鍏ュ懆鏈熸暟鍊�(濡�:瑕佽缃浘琛ㄥ懆鏈熶负5鍒嗛挓锛岃杈撳叆5).鏁板€煎悗鍙姞瀛楁瘝H浠ｈ〃灏忔椂锛屽姞D浠ｈ〃鏃ワ紝W浠ｈ〃鍛紝M浠ｈ〃鏈�",
    "Not applicable": "涓嶉€傜敤",
    "Stats Text Color": "缁熻鏂囨湰棰滆壊",
    "Show Angle": "鏄剧ず瑙掑害",
    "Always Show Stats": "鎬绘樉绀虹粺璁�",
    "Rename...": "閲嶅懡鍚�...",
    "Load": "鍔犺浇",
    "Save": "淇濆瓨",
    "Rename Chart": "閲嶅懡鍚嶅浘琛�",
    "{0} copy": "{0} 澶嶅埗",
    "Please enter chart name": "璇疯緭鍏ュ浘琛ㄥ悕绉�",
    "Enter a new chart name": "杈撳叆涓€涓柊鐨勫浘琛ㄥ悕绉�",
    "Load Chart": "鍔犺浇鍥捐〃",
    "Chart Name": "鍥捐〃鍚嶇О",
    "Chart name": "鍥捐〃鍚嶇О",
    "Last Modified": "鏈€鍚庝慨鏀�",
    "Active Symbol": "娲昏穬鍟嗗搧",
    "Fullscreen mode": "鍏ㄥ睆妯″紡",
    "Marker Color": "鏍囪棰滆壊",
    "Font Size": "瀛椾綋澶у皬",
    "Save New Chart": "淇濆瓨鏂扮殑鍥捐〃",
    "Source_compare": "鏉ユ簮",
    "YES": "鏄�",
    "NO": "鍚�",
    "Confirmation": "纭",
    "Are you sure you want to delete this chart?": "鎮ㄧ‘瀹氳鍒犻櫎杩欎釜鍥捐〃锛�"
}